apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: docker.io/talhaabdurrahman/session-backend:latest
          name: backend
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: 8000
      hostname: backend-service
